### ISSUE TITLE
Kodi crash and cec broken when pogramming exit key

### ISSUE THREAD

**Issue by cvandeplas** [hissingshark/retrOSMCmk2#27]
When programming the CEC exit key kodi crashes and CEC breaks. Kodi 19.5, on latest OSMC and raspberry pi 4 
Also the CEC remote is completely broken due to the  `remote_jammer("START")` and `remote_jammer("STOP")` not being in a `try finally` section. As kodi crashes before `remote_jammer("STOP")` is called, the `remote.xml` is not restored.
This can be solved by manually copying over the `/home/osmc/.kodi/userdata/keymaps/remote.xml.hidden` file to `remote.xml` and restarting kodi.

With debug mode and CEC debugging on, `kodi.log` (I've removed some repetitive messages)
```
2023-05-28 06:35:19.343 T:3947     INFO <general>: retrOSMCmk2 Launcher: "/home/osmc/.kodi/userdata/addon_data/script.launch.retropie/data.xml" missing or corrupt on this run
2023-05-28 06:35:19.358 T:3876    DEBUG <general>: ------ Window Init (DialogConfirm.xml) ------
2023-05-28 06:35:19.358 T:3876     INFO <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
########### User now needs to press the remote button repetitively
2023-05-28 06:35:29.240 T:3901    DEBUG <general>: CecLogMessage - CLinuxCECAdapterCommunication::Process - ioctl CEC_RECEIVE - rx_status=01 len=3 addr=04 opcode=44
2023-05-28 06:35:29.240 T:3901    DEBUG <general>: CecLogMessage - >> 04:44:00
2023-05-28 06:35:29.240 T:3901    DEBUG <general>: CecLogMessage - SetCurrentButton select (0) D:0ms cur:0
2023-05-28 06:35:29.240 T:3901    DEBUG <general>: CecLogMessage - key pressed: select (0) current(ff) duration(0)
2023-05-28 06:35:29.240 T:3901    DEBUG <general>: CecLogMessage - Changed key select (0) D:0ms cur:ff
2023-05-28 06:35:29.240 T:3901    DEBUG <general>: CecLogMessage - key pressed: select (0, 0)
2023-05-28 06:35:29.240 T:3901    DEBUG <general>: PushCecKeypress - received key  b duration 0
2023-05-28 06:35:29.240 T:3901    DEBUG <general>: CecLogMessage - CheckKeypressTimeout T:30109.681
2023-05-28 06:35:29.240 T:3901    DEBUG <general>: CecLogMessage - Key select: idle (duration:0) (0) timeout:-267349584ms (rel:500,rep:0,prs:500,rel:0)
2023-05-28 06:35:29.240 T:3901    DEBUG <general>: CecLogMessage - >> TV (0) -> Playback 1 (4): user control pressed (44)
2023-05-28 06:35:29.243 T:3876    DEBUG <general>: HandleKey: 11 (0x0b, obc244) pressed, action is Select
2023-05-28 06:35:29.315 T:3901    DEBUG <general>: CecLogMessage - CLinuxCECAdapterCommunication::Process - ioctl CEC_RECEIVE - rx_status=01 len=2 addr=04 opcode=45
2023-05-28 06:35:29.315 T:3901    DEBUG <general>: CecLogMessage - >> 04:45
2023-05-28 06:35:29.315 T:3901    DEBUG <general>: CecLogMessage - key released: select (0) D:75ms
2023-05-28 06:35:29.315 T:3901    DEBUG <general>: PushCecKeypress - received key  b duration 75
2023-05-28 06:35:29.315 T:3901    DEBUG <general>: CecLogMessage - >> TV (0) -> Playback 1 (4): user control release (45)
2023-05-28 06:35:29.505 T:3876    DEBUG <general>: ------ Window Deinit (DialogConfirm.xml) ------
2023-05-28 06:35:30.197 T:3876     INFO <general>: Loading special://xbmc/system/keymaps/appcommand.xml
2023-05-28 06:35:30.199 T:3876     INFO <general>: Loading special://xbmc/system/keymaps/customcontroller.AppleRemote.xml
2023-05-28 06:35:30.201 T:3876     INFO <general>: Loading special://xbmc/system/keymaps/customcontroller.Harmony.xml
2023-05-28 06:35:30.204 T:3876     INFO <general>: Loading special://xbmc/system/keymaps/customcontroller.SiriRemote.xml
2023-05-28 06:35:30.205 T:3876     INFO <general>: Loading special://xbmc/system/keymaps/gamepad.xml
2023-05-28 06:35:30.207 T:3876     INFO <general>: Loading special://xbmc/system/keymaps/hama_mce.xml
2023-05-28 06:35:30.208 T:3876     INFO <general>: Loading special://xbmc/system/keymaps/joystick.xml
2023-05-28 06:35:30.210 T:3876     INFO <general>: Loading special://xbmc/system/keymaps/keyboard.xml
2023-05-28 06:35:30.215 T:3876     INFO <general>: Loading special://xbmc/system/keymaps/mouse.xml
2023-05-28 06:35:30.215 T:3876     INFO <general>: Loading special://xbmc/system/keymaps/osmc_classic.xml
2023-05-28 06:35:30.216 T:3876     INFO <general>: Loading special://xbmc/system/keymaps/remote.xml
2023-05-28 06:35:30.219 T:3876     INFO <general>: Loading special://xbmc/system/keymaps/touchscreen.xml
2023-05-28 06:35:30.221 T:3876     INFO <general>: Loading special://masterprofile/keymaps/remote.xml
2023-05-28 06:35:30.221 T:3876    ERROR <general>: Remote Translator: Can't find button exit
2023-05-28 06:35:30.222 T:3876     INFO <general>: Loading special://profile/keymaps/remote.xml
2023-05-28 06:35:30.223 T:3876    ERROR <general>: Remote Translator: Can't find button exit
2023-05-28 06:35:30.223 T:3876    DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
2023-05-28 06:35:30.430 T:3901    DEBUG <general>: CecLogMessage - CLinuxCECAdapterCommunication::Process - ioctl CEC_RECEIVE - rx_status=01 len=3 addr=04 opcode=44
2023-05-28 06:35:30.431 T:3901    DEBUG <general>: CecLogMessage - >> 04:44:2c
2023-05-28 06:35:30.431 T:3901    DEBUG <general>: CecLogMessage - SetCurrentButton clear (2c) D:0ms cur:2c
2023-05-28 06:35:30.431 T:3901    DEBUG <general>: CecLogMessage - key pressed: clear (2c) current(ff) duration(0)
2023-05-28 06:35:30.431 T:3901    DEBUG <general>: CecLogMessage - Changed key clear (2c) D:0ms cur:ff
2023-05-28 06:35:30.432 T:3901    DEBUG <general>: CecLogMessage - key pressed: clear (2c, 0)
2023-05-28 06:35:30.432 T:3901    DEBUG <general>: PushCecKeypress - received key f9 duration 0
2023-05-28 06:35:30.432 T:3901    DEBUG <general>: CecLogMessage - CheckKeypressTimeout T:30110.872
2023-05-28 06:35:30.432 T:3901    DEBUG <general>: CecLogMessage - Key clear: idle (duration:0) (2c) timeout:-267349584ms (rel:500,rep:0,prs:500,rel:0)
2023-05-28 06:35:30.432 T:3901    DEBUG <general>: CecLogMessage - >> TV (0) -> Playback 1 (4): user control pressed (44)
2023-05-28 06:35:30.438 T:3876    DEBUG <general>: HandleKey: 249 (0xf9, obc6) pressed, action is 
2023-05-28 06:35:30.637 T:3901    DEBUG <general>: CecLogMessage - CLinuxCECAdapterCommunication::Process - ioctl CEC_RECEIVE - rx_status=01 len=2 addr=04 opcode=45
2023-05-28 06:35:30.637 T:3901    DEBUG <general>: CecLogMessage - >> 04:45
2023-05-28 06:35:30.637 T:3901    DEBUG <general>: CecLogMessage - key released: clear (2c) D:206ms
2023-05-28 06:35:30.637 T:3901    DEBUG <general>: PushCecKeypress - received key f9 duration 206
2023-05-28 06:35:30.638 T:3901    DEBUG <general>: CecLogMessage - >> TV (0) -> Playback 1 (4): user control release (45)
2023-05-28 06:35:31.038 T:3901    DEBUG <general>: CecLogMessage - CLinuxCECAdapterCommunication::Process - ioctl CEC_RECEIVE - rx_status=01 len=3 addr=04 opcode=44
2023-05-28 06:35:31.038 T:3901    DEBUG <general>: CecLogMessage - >> 04:44:2c
2023-05-28 06:35:31.038 T:3901    DEBUG <general>: CecLogMessage - SetCurrentButton clear (2c) D:0ms cur:2c
2023-05-28 06:35:31.038 T:3901    DEBUG <general>: CecLogMessage - key pressed: clear (2c) current(ff) duration(0)
2023-05-28 06:35:31.039 T:3901    DEBUG <general>: CecLogMessage - Changed key clear (2c) D:0ms cur:ff
2023-05-28 06:35:31.039 T:3901    DEBUG <general>: CecLogMessage - key pressed: clear (2c, 0)
2023-05-28 06:35:31.039 T:3901    DEBUG <general>: PushCecKeypress - received key f9 duration 0
2023-05-28 06:35:31.039 T:3901    DEBUG <general>: CecLogMessage - CheckKeypressTimeout T:30111.479
2023-05-28 06:35:31.039 T:3901    DEBUG <general>: CecLogMessage - Key clear: idle (duration:0) (2c) timeout:-267349584ms (rel:500,rep:0,prs:500,rel:0)

<snip - many times press of f9 key>

2023-05-28 06:35:40.767 T:3947    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'StopIteration'>
                                                   Traceback (most recent call last):
                                                     File "/home/osmc/.kodi/addons/script.launch.retropie/addon.py", line 453, in <module>
                                                       keys.append(cec_client("CODE"))
                                                     File "/home/osmc/.kodi/addons/script.launch.retropie/addon.py", line 28, in cec_client
                                                       line = next(cecc_iter)
                                                   StopIteration
                                                   -->End of Python script error report<--
                                                   
2023-05-28 06:35:40.767 T:3947    DEBUG <general>: onExecutionDone(5, /home/osmc/.kodi/addons/script.launch.retropie/addon.py)
2023-05-28 06:35:40.798 T:3876    DEBUG <general>: ------ Window Init (DialogNotification.xml) ------
```

Checking the while loop of the `` function I notice that the `CecLogMessage - >> 04:44:2c` are not captured by `      line = next(cecc_iter)`. This is caused because CEC messages are still received by kodi, and not by the subprocess that is supposed to be spawned. (`cecc_proc = subprocess.Popen(CLIENT, stdout=subprocess.PIPE, universal_newlines=True)`)

Not sure yet on how to address this: either capture the CEC message through Kodi's interface. Or release CEC completely from kodi and capture it using the subprocess as it is done today.

**Comment by cvandeplas** [comment]
Disabling CEC in the Settings > System > Input > Peripherals > CEC > Enabled (off) , and restarting Kodi results in a correct capture of the CEC code and `data.xml` is written correctly.
After the message saying it is captured kodi still crashes. No stack trace found in `kodi.log`.

**Comment by hissingshark** [comment]
Not tested on RPi4, but regardless I think this will be due to python changes.  I'm in the process of replacing the now depreciated `subprocess.Popen` methods.  They may be failing, which is why you are experiencing the problems.
That said, my CEC code was written, tested and working on my Samsung years ago.  I can't use it on my LG due to the poorer CEC support, so I tend to use the controller/evdev exit method myself.

**Comment by mdkeil** [comment]
I'm facing the same challenge. When saving the exit key (TV remote), Kodi crashes, and I can't configure the controller exit key because I keep getting a message that no controller is found - even though I am controlling the Vero V with one. I'm using an 8BitDo SN30 Bluetooth SNES controller.
